[runtime]
storage = "/tmp/webbed-duck-storage"

[server]
host = "127.0.0.1"
port = 8000
source_dir = "routes_src"
build_dir = "routes_build"
auto_compile = true
watch = false
plugins_dir = "plugins"

[server.constants]
data_root = "./data"
